//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNCT_TNP_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudentAcademic
    {
        public int Id { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string SSC_Percentage { get; set; }
        public string SSC_SchoolName { get; set; }
        public string SSC_Board { get; set; }
        public string SSC_YOP { get; set; }
        public string HSC_Percentage { get; set; }
        public string HSC_SchoolName { get; set; }
        public string HSC_Board { get; set; }
        public string HSC_YOP { get; set; }
        public string Diploma_Percentage { get; set; }
        public string Diploma_YOP { get; set; }
        public string UG_Percentage { get; set; }
        public string UG_YOP { get; set; }
        public string UG_Back { get; set; }
        public string UG_YearGap { get; set; }
        public string PG_Percentage { get; set; }
        public string PG_YOP { get; set; }
        public string PG_Back { get; set; }
        public string PG_YearGap { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> BranchID { get; set; }
    
        public virtual TblBranch TblBranch { get; set; }
        public virtual TblCourse TblCourse { get; set; }
        public virtual TblDepartment TblDepartment { get; set; }
        public virtual TblStudentRegister TblStudentRegister { get; set; }
    }
}
