//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNCT_TNP_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStudentProfile
    {
        public int Id { get; set; }
        public string EmailId { get; set; }
        public string MobileNo { get; set; }
        public string FatherName { get; set; }
        public string CurrentAddress { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual TblBranch TblBranch { get; set; }
        public virtual TblCourse TblCourse { get; set; }
        public virtual TblDepartment TblDepartment { get; set; }
        public virtual TblStudentRegister TblStudentRegister { get; set; }
    }
}
